module IABConsentString
  module GDPRConstantsV2
    class Core
      VERSION_BIT_OFFSET = 0
      VERSION_BIT_SIZE = 6
      CREATED_BIT_OFFSET = 6
      CREATED_BIT_SIZE = 36
      UPDATED_BIT_OFFSET = 42
      UPDATED_BIT_SIZE = 36
      CMP_ID_OFFSET = 78
      CMP_ID_SIZE = 12
      CMP_VERSION_OFFSET = 90
      CMP_VERSION_SIZE = 12
      CONSENT_SCREEN_SIZE_OFFSET = 102
      CONSENT_SCREEN_SIZE = 6
      CONSENT_LANGUAGE_OFFSET = 108
      CONSENT_LANGUAGE_SIZE = 12
      VENDOR_LIST_VERSION_OFFSET = 120
      VENDOR_LIST_VERSION_SIZE = 12
      TCF_POLICY_VERSION_OFFSET = 132
      TCF_POLICY_VERSION_SIZE = 6
      IS_SERVICE_SPECIFIC_OFFSET = 138
      IS_SERVICE_SPECIFIC_SIZE = 1
      USE_NON_STANDARD_STACKS_OFFSET = 139
      USE_NON_STANDARD_STACKS_SIZE = 1
      SPECIAL_FEATURE_OPT_INS_OFFSET = 140 
      SPECIAL_FEATURE_OPT_INS_SIZE = 12
      PURPOSES_CONSENT_OFFSET = 152
      PURPOSES_CONSENT_SIZE = 24
      PURPOSES_LI_TRANSPARENCY_OFFSET = 176
      PURPOSES_LI_TRANSPARENCY_SIZE = 24
      # Specific Jurisdiction Disclosures
      PURPOSE_ONE_TREATMENT_OFFSET = 200
      PURPOSE_ONE_TREATMENT_SIZE = 1
      PUBLISHER_CC_OFFSET = 201
      PUBLISHER_CC_SIZE = 12
      #Vendor section
      VENDOR_START_SECTION_OFFSET = 213
      MAX_VENDOR_ID_SIZE = 16
      VENDOR_IS_RANGE_ENCODING_OFFSET = 16
      VENDOR_SECTION_OFFSET = 17
      VENDOR_RANGE_NUM_ENTRY_SIZE = 12
      VENDOR_ID_SIZE = 16
      #Publisher restriction
      NUM_PUB_RESTRICTIONS_SIZE = 12
      PURPOSE_ID_SIZE = 6
      RESTRICTION_TYPE_SIZE = 2
    end

    class Segment
      SEGMENT_TYPE_SIZE = 3
      SEGMENT_TYPE_OFFSET = 0
      VENDOR_START_SECTION_OFFSET = 3
    end

    class PubPurposesTransparency
      PUB_PURPOSES_CONSENT_SIZE = 24
      PUB_PURPOSES_CONSENT_OFFSET = 3
      PUB_PURPOSES_LI_TRANSPARENCY_SIZE = 24
      PUB_PURPOSES_LI_TRANSPARENCY_OFFSET = 27
      NUM_CUSTOM_PURPOSES_OFFSET = 51
      NUM_CUSTOM_PURPOSES_SIZE = 6
      CUSTOM_PURPOSES_OFFSET = 57
    end
  end
end
