module IABConsentString
  class GDPRConstants
    VENDOR_ENCODING_RANGE = 1
    VERSION_BIT_OFFSET = 0
    VERSION_BIT_SIZE = 6
    CREATED_BIT_OFFSET = 6
    CREATED_BIT_SIZE = 36
    UPDATED_BIT_OFFSET = 42
    UPDATED_BIT_SIZE = 36
    CMP_ID_OFFSET = 78
    CMP_ID_SIZE = 12
    CMP_VERSION_OFFSET = 90
    CMP_VERSION_SIZE = 12
    CONSENT_SCREEN_SIZE_OFFSET = 102
    CONSENT_SCREEN_SIZE = 6
    CONSENT_LANGUAGE_OFFSET = 108
    CONSENT_LANGUAGE_SIZE = 12
    VENDOR_LIST_VERSION_OFFSET = 120
    VENDOR_LIST_VERSION_SIZE = 12
    PURPOSES_OFFSET = 132
    PURPOSES_SIZE = 24
    MAX_VENDOR_ID_OFFSET = 156
    MAX_VENDOR_ID_SIZE = 16
    ENCODING_TYPE_OFFSET = 172
    ENCODING_TYPE_SIZE = 1
    VENDOR_BITFIELD_OFFSET = 173
    DEFAULT_CONSENT_OFFSET = 173
    NUM_ENTRIES_OFFSET = 174
    NUM_ENTRIES_SIZE = 12
    RANGE_ENTRY_OFFSET = 186
    VENDOR_ID_SIZE = 16
  end
end
