module IABConsentString
  module GDPRConstantsV2
    class Core
      VERSION_BIT_OFFSET = 0
      VERSION_BIT_SIZE = 6
      CREATED_BIT_OFFSET = 6
      CREATED_BIT_SIZE = 36
      UPDATED_BIT_OFFSET = 42
      UPDATED_BIT_SIZE = 36
      CMP_ID_OFFSET = 78
      CMP_ID_SIZE = 12
      CMP_VERSION_OFFSET = 90
      CMP_VERSION_SIZE = 12
      CONSENT_SCREEN_SIZE_OFFSET = 102
      CONSENT_SCREEN_SIZE = 6
      CONSENT_LANGUAGE_OFFSET = 108
      CONSENT_LANGUAGE_SIZE = 12
      VENDOR_LIST_VERSION_OFFSET = 120
      VENDOR_LIST_VERSION_SIZE = 12
      TCF_POLICY_VERSION_OFFSET = 132
      TCF_POLICY_VERSION_SIZE = 6
      IS_SERVICE_SPECIFIC_OFFSET = 138
      IS_SERVICE_SPECIFIC_SIZE = 1
      USE_NON_STANDARD_STACKS_OFFSET = 139
      USE_NON_STANDARD_STACKS_SIZE = 1
      SPECIAL_FEATURE_OPT_INS_OFFSET = 140 
      SPECIAL_FEATURE_OPT_INS_SIZE = 12
      PURPOSES_CONSENT_OFFSET = 152
      PURPOSES_CONSENT_SIZE = 24
      PURPOSES_LI_TRANSPARENCY_OFFSET = 176
      PURPOSES_LI_TRANSPARENCY_SIZE = 24
    end
  end
end
